version: '3.7'
secrets:
  db_mysql_user_password:
    file: ./env
services:
    mysql:
        build:
            context: .
            dockerfile: Dockerfile.mysql
        environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD=1
            - MYSQL_PASSWORD_FILE=/run/secrets/db_mysql_user_password
            #- MYSQL_DBUSER_PASSWORD=cat $("/run/secrets/db_mysql_user_password")
        secrets:
            - db_mysql_user_password
        ports:
            - 3308:3308
        restart: always
    flask:
        build:
            context: .
            dockerfile: Dockerfile.flask
        depends_on:
            - "mysql"
        ports:
            - 5000:5000
        environment:
            - MYSQL_PASSWORD_FILE=/run/secrets/db_mysql_user_password
        secrets:
            - db_mysql_user_password